version: '3.8'

services:
  mysql:
    container_name: almazara-mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
      - db:/var/lib/mysql
    networks:
      - default

  backend:
    container_name: almazara-backend
    build: ./backend
    ports:
      - '4000:4000'
    networks:
      - default

  frontend:
    container_name: almazara-frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:5173'
    networks:
      - default

volumes:
  db:
