version: '3.8'

services:
  backend:
    container_name: almazara-backend
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5000:5000'
    environment:
      - RDS_HOST=database-1.cettw0uuspvz.us-east-1.rds.amazonaws.com
      - RDS_USERNAME=d3vel0p3r
      - RDS_PASSWORD=developer
      - RDS_DATABASE=almazara_dev
      - RDS_PORT=3306
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  frontend:
    container_name: almazara-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - '3000:3000'
    networks:
      - frontend

networks:
  backend:
  frontend:
